#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_mark(tbl_mark instance);
  partial void Updatetbl_mark(tbl_mark instance);
  partial void Deletetbl_mark(tbl_mark instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_mark> tbl_marks
	{
		get
		{
			return this.GetTable<tbl_mark>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_marks")]
public partial class tbl_mark : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _name;
	
	private System.Nullable<System.DateTime> _date_;
	
	private System.Nullable<int> _marks_;
	
	private System.Nullable<int> _obtains_;
	
	private string _file_path;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Ondate_Changing(System.Nullable<System.DateTime> value);
    partial void Ondate_Changed();
    partial void Onmarks_Changing(System.Nullable<int> value);
    partial void Onmarks_Changed();
    partial void Onobtains_Changing(System.Nullable<int> value);
    partial void Onobtains_Changed();
    partial void Onfile_pathChanging(string value);
    partial void Onfile_pathChanged();
    #endregion
	
	public tbl_mark()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_", DbType="Date")]
	public System.Nullable<System.DateTime> date_
	{
		get
		{
			return this._date_;
		}
		set
		{
			if ((this._date_ != value))
			{
				this.Ondate_Changing(value);
				this.SendPropertyChanging();
				this._date_ = value;
				this.SendPropertyChanged("date_");
				this.Ondate_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marks_", DbType="Int")]
	public System.Nullable<int> marks_
	{
		get
		{
			return this._marks_;
		}
		set
		{
			if ((this._marks_ != value))
			{
				this.Onmarks_Changing(value);
				this.SendPropertyChanging();
				this._marks_ = value;
				this.SendPropertyChanged("marks_");
				this.Onmarks_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obtains_", DbType="Int")]
	public System.Nullable<int> obtains_
	{
		get
		{
			return this._obtains_;
		}
		set
		{
			if ((this._obtains_ != value))
			{
				this.Onobtains_Changing(value);
				this.SendPropertyChanging();
				this._obtains_ = value;
				this.SendPropertyChanged("obtains_");
				this.Onobtains_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_path", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string file_path
	{
		get
		{
			return this._file_path;
		}
		set
		{
			if ((this._file_path != value))
			{
				this.Onfile_pathChanging(value);
				this.SendPropertyChanging();
				this._file_path = value;
				this.SendPropertyChanged("file_path");
				this.Onfile_pathChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
